POST https://localhost:7073/catalog
Content-Type: application/json

{
    "name": "Milk",
    "description" : "Best of Cows",
    "quantity" : 100,
    "type":"Tangable",
    "price":1.20
}

###
POST https://localhost:7073/catalog
Content-Type: application/json

{
    "name": "Bread",
    "description" : "Easy Toast",
    "quantity" : 100,
    "type":"Tangable",
    "price":1.00
}

###
POST https://localhost:7073/catalog
Content-Type: application/json

{
    "name": "Eggs",
    "description" : "Wild chicken",
    "quantity" : 500,
    "type":"Tangable",
    "price":0.20
}